lib/group_kit_web/router.ex
defmodule GroupKitWeb.Router do
  use GroupKitWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug GroupKitWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GroupKitWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/manage", GroupKitWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/members", MemberController
  end

  # Other scopes may use custom stacks.
  # scope "/api", GroupKitWeb do
  #   pipe_through :api
  # end
end

lib/group_kit_web/views/layout_view.ex
defmodule GroupKitWeb.LayoutView do
  use GroupKitWeb, :view
end

lib/group_kit_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "GroupKit · Phoenix Framework" %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body class="font-sans text-base antialiased bg-gray-100 text-gray-800 mx-10 my-3">
    <header>
        <section class="container">
          <nav role="navigation">
          <ul>
          <%= if @current_user do %>
          <li><%= @current_user.username %></li>
          <li>
          <%= link "Log out",
          to: Routes.session_path(@conn, :delete, @current_user),
          method: "delete" %>
          </li>
          <% else %>
          <li><%= link "Register", to: Routes.user_path(@conn, :new) %></li>
          <li><%= link "Log in", to: Routes.session_path(@conn, :new) %></li>
          <% end %>
          </ul>
          </nav>
          </section>
    </header>
    <main role="main">
      <p class="" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>